### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by droidxna** [Fqwe1/Ukrainian-blocklists#1]
Need a separeted lists of blocked sites from https://uablocklist.com/blocklist with ip addresses which may looks like https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt for creating ipset for firewall.
Same 3 lists, only, with IP`s.
Advanced thanks.

**Comment by Fqwe1** [comment]
Done

**Comment by droidxna** [comment]
Thanks.

нд, 7 січ. 2024 р. о 18:46 Fqwe1 ***@***.***> пише:
