### ISSUE TITLE
Database have forbidden for dns names symbols

### ISSUE THREAD

**Issue by droidxna** [Fqwe1/Ukrainian-blocklists#2]
03:04:45 | ipfire: | uablocklist.com updated, DNS reloaded
03:03:58 | ipfire: | \|\|team&#8211;shop.com^SKIPPED
03:03:58 | ipfire: | Produce filters for unbound dns filtering
03:03:58 | ipfire: | Updated rnbo
03:02:51 | ipfire: | Updated nkrzi
03:01:37 | ipfire: | Updated ema
03:01:00 | ipfire: | Start update uablocklist.com

**Comment by Fqwe1** [comment]
EMA Blocklist is available only for Adblockers, because [the site](https://ema.com.ua/) does not add IP addresses

**Comment by droidxna** [comment]
In anyway, thanks. nkrzi & rnbo ipset will be sufficient.

пн, 8 січ. 2024 р. о 08:24 Fqwe1 ***@***.***> пише:
