### ISSUE TITLE
Missing requrement module in requirements.txt

### ISSUE THREAD

**Issue by droidxna** [Fqwe1/Ukrainian-blocklists#3]
(sbu) root@openscada:/sbu/Ukrainian-blocklists# /sbu/bin/python3 parsers/ema.py
Traceback (most recent call last):
  File "/sbu/Ukrainian-blocklists/parsers/ema.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
(sbu) root@openscada:/sbu/Ukrainian-blocklists# /sbu/bin/pip3 install requests
Collecting requests
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 402.2 kB/s eta 0:00:00
Requirement already satisfied: charset-normalizer<4,>=2 in /sbu/lib/python3.11/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /sbu/lib/python3.11/site-packages (from requests) (3.6)
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.1.0-py3-none-any.whl (104 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.6/104.6 kB 271.6 kB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2023.11.17-py3-none-any.whl (162 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.5/162.5 kB 70.4 kB/s eta 0:00:00
Installing collected packages: urllib3, certifi, requests
Successfully installed certifi-2023.11.17 requests-2.31.0 urllib3-2.1.0
(sbu) root@openscada:/sbu/Ukrainian-blocklists# /sbu/bin/python3 parsers/ema.py
(sbu) root@openscada:/sbu/Ukrainian-blocklists# /sbu/bin/python3 parsers/nkrzi.py
(sbu) root@openscada:/sbu/Ukrainian-blocklists# /sbu/bin/python3 parsers/rnbo.py
(sbu) root@openscada:/sbu/Ukrainian-blocklists# /sbu/bin/python3 parsers/rnbo_ip.py
(sbu) root@openscada:/sbu/Ukrainian-blocklists# /sbu/bin/python3 parsers/nkrzi_ip.py
(sbu) root@openscada:/sbu/Ukrainian-blocklists# ls blocklists/
ema.txt  nkrzi_ip.txt  nkrzi.txt  rnbo_ip.txt  rnbo.txt

**Comment by Fqwe1** [comment]
Done

**Comment by droidxna** [comment]
Thanks

пн, 8 січ. 2024 р. о 08:21 Fqwe1 ***@***.***> пише:
